name: .NET Core Release

on:
  release:
    types: [published]

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      release_all: ${{ steps.tag.outputs.release_all }}
      release_core: ${{ steps.tag.outputs.release_core }}
      release_templates: ${{ steps.tag.outputs.release_templates }}
      release_version:  ${{ steps.version.outputs.release_version }}
    steps:
      - name: Check the tag ${{ github.ref }}
        id: tag
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/all@v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=release_all::true"
          else
            echo "::set-output name=release_all::false"
          fi
          if [[ ${{ github.ref }} =~ refs\/tags\/core@v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=release_core::true"
          else
            echo "::set-output name=release_core::false"
          fi
          if [[ ${{ github.ref }} =~ refs\/tags\/templates@v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=release_templates::true"
          else
            echo "::set-output name=release_templates::false"
          fi
      - name: Get the version
        id: version
        run: echo "::set-output name=release_version::${GITHUB_REF#refs/tags/*@v}"
  release_core:
    needs: check_tag
    if: (needs.check_tag.outputs.release_all == 'true') || (needs.check_tag.outputs.release_core == 'true')
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Build Core
        run: dotnet build ./src/WebFrame
      - name: Build Tests
        run: dotnet build ./tests/WebFrame.Tests
      - name: Test with the dotnet CLI
        run: dotnet test -v m ./tests/WebFrame.Tests
      - run: dotnet build --configuration Release ./src/WebFrame/WebFrame.fsproj
      - name: Create the package
        run: dotnet paket pack --template ./src/WebFrame/paket.template --specific-version RussBaz.WebFrame ${{ needs.check_tag.outputs.release_version }} --build-config Release .
      - name: Publish the package to nuget
        run: dotnet nuget push ./*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
      - name: Remove nuget packages
        run: rm -f *.nupkg
  release_templates:
    needs: check_tag
    if: (needs.check_tag.outputs.release_all == 'true') || (needs.check_tag.outputs.release_templates == 'true')
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - run: dotnet build --configuration Release ./templates/templatepack.fsproj
      - name: Create the package
        run: dotnet pack ./templates/templatepack.fsproj -c Release -p:PackageVersion=${{ needs.check_tag.outputs.release_version }} -o .
      - name: Publish the package to nuget
        run: dotnet nuget push ./*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
      - name: Remove nuget packages
        run: rm -f *.nupkg